version: "3.5"
services: 
  postgres:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    env_file:
      - .development.env
    container_name: postgres
    networks:
      - rsschool
    volumes:
      - db:/var/lib/postresql/data
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    env_file:
      - .development.env
    container_name: "app"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./src:/usr/src/app/src
      - logs:/usr/src/app/logs
    networks:
      - rsschool
networks:
  rsschool:
    driver: bridge
volumes:
  logs:
  db: