version: "3.8"
services: 
  postgres:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    container_name: "postgres"
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: "app"
    depends_on:
      - postgres
    ports: 
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs
    restart: always
    env_file:
      - .env