version: "3.5"
services: 
  postgres:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    container_name: ${POSTGRES_HOST}
    networks:
      - rsschool
    environment: 
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: "app"
    depends_on:
      - postgres
    ports: 
      - ${PORT}:${PORT}
    restart: always
    volumes:
      - ./src:/usr/src/app/src
      - logs:/usr/src/app/logs
    env_file:
      - .env
    networks:
      - rsschool
networks:
  rsschool:
    driver: bridge
volumes:
  logs:
  db: