version: "3.8"
services: 
  postgres:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    container_name: "postgres"
    environment: 
      - PG_DATA=/var/lib/postresql/data
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: "app"
    depends_on:
      - postgres
    ports: 
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src
    restart: always