version: "3.8"
services: 
  postgres:
    image: postgres:alpine
    container_name: "postgres"
    environment: 
      - PG_DATA=/var/lib/postresql/data
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    build: .
    container_name: "app"
    depends_on:
      - postgres
    ports: 
      - "4000:4000"
    volumes:
      - ./src:/app/src
    restart: always